version: '1.0'

services:
  sample-prod:
    container_name: s-libres
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.s-libres.entrypoints=web,websecure"
      - "traefik.http.routers.s-libres.rule=Host(`salles.cyberlog.dev`)"
      - "traefik.http.services.s-libres.loadbalancer.server.port=80"
      - "traefik.http.routers.s-libres.tls=true"
      - "traefik.http.routers.s-libres.tls.certresolver=lets-encrypt"

networks:
    web:
        external: true