version: '3.3'

services:
  sample-prod:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.api.entrypoints=web,websecure"
      - "traefik.http.routers.api.rule=Host(`api.cyberlog.dev`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=lets-encrypt"
    restart: unless-stopped

networks:
  web:
    external: true
